const express = require('express');
const router = express.Router();
const reportService = require('../services/reportService');
const { authenticateToken } = require('../middleware/auth');
const logger = require('../utils/logger');

// 鑾峰彇鎵€鏈夋姤琛?
router.get('/', authenticateToken, async (req, res, next) => {
  try {
    const { limit } = req.query;
    const reports = await reportService.getAllReports(limit ? parseInt(limit) : 50);
    
    res.json({
      success: true,
      data: reports
    });
  } catch (error) {
    next(error);
  }
});

// 鑾峰彇鎸囧畾鎶ヨ〃
router.get('/meta/types', authenticateToken, (req, res) => {
  const types = reportService.getReportTypes();
  res.json({
    success: true,
    data: types.map(type => ({
      value: type,
      label: type.charAt(0).toUpperCase() + type.slice(1)
    }))
  });
});

router.get('/:reportId', authenticateToken, async (req, res, next) => {
  try {
    const { reportId } = req.params;
    const report = await reportService.getReport(reportId);
    
    if (!report) {
      return res.status(404).json({
        success: false,
        error: {
          code: 'REPORT_NOT_FOUND',
          message: 'Report not found'
        }
      });
    }

    res.json({
      success: true,
      data: report
    });
  } catch (error) {
    next(error);
  }
});

// 鐢熸垚鑷畾涔夋姤琛?
router.post('/generate', authenticateToken, async (req, res, next) => {
  try {
    const { nodeIds, startTime, endTime, metrics } = req.body;

    // 楠岃瘉蹇呭～瀛楁
    if (!nodeIds || !Array.isArray(nodeIds) || nodeIds.length === 0) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'MISSING_FIELDS',
          message: 'Node IDs are required'
        }
      });
    }

    if (!startTime || !endTime) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'MISSING_FIELDS',
          message: 'Start time and end time are required'
        }
      });
    }

    // 楠岃瘉鏃堕棿鑼冨洿
    const start = new Date(startTime);
    const end = new Date(endTime);
    
    if (isNaN(start.getTime()) || isNaN(end.getTime())) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'INVALID_TIME',
          message: 'Invalid time format'
        }
      });
    }

    if (start >= end) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'INVALID_TIME_RANGE',
          message: 'Start time must be before end time'
        }
      });
    }

    // 鐢熸垚鎶ヨ〃
    const report = await reportService.generateReport({
      type: 'custom',
      nodeIds,
      startTime,
      endTime,
      metrics,
      userId: req.user.user_id
    });

    logger.info(`Custom report generated by user ${req.user.username}: ${report.id}`);

    res.json({
      success: true,
      data: report,
      message: 'Report generated successfully'
    });
  } catch (error) {
    next(error);
  }
});

// 鐢熸垚棰勫畾涔夋姤琛紙鏃ユ姤銆佸懆鎶ャ€佹湀鎶ワ級
router.post('/generate/:type', authenticateToken, async (req, res, next) => {
  try {
    const { type } = req.params;
    const { nodeIds } = req.body;

    // 楠岃瘉鎶ヨ〃绫诲瀷
    const validTypes = reportService.getReportTypes();
    if (!validTypes.includes(type)) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'INVALID_TYPE',
          message: `Report type must be one of: ${validTypes.join(', ')}`
        }
      });
    }

    // 楠岃瘉鑺傜偣ID
    if (!nodeIds || !Array.isArray(nodeIds) || nodeIds.length === 0) {
      return res.status(400).json({
        success: false,
        error: {
          code: 'MISSING_FIELDS',
          message: 'Node IDs are required'
        }
      });
    }

    // 鐢熸垚鎶ヨ〃
    const report = await reportService.generatePredefinedReport(
      type,
      nodeIds,
      req.user.user_id
    );

    logger.info(`${type} report generated by user ${req.user.username}: ${report.id}`);

    res.json({
      success: true,
      data: report,
      message: `${type.charAt(0).toUpperCase() + type.slice(1)} report generated successfully`
    });
  } catch (error) {
    next(error);
  }
});

// 鍒犻櫎鎶ヨ〃
router.delete('/:reportId', authenticateToken, async (req, res, next) => {
  try {
    const { reportId } = req.params;

    // 妫€鏌ユ姤琛ㄦ槸鍚﹀瓨鍦?
    const report = await reportService.getReport(reportId);
    if (!report) {
      return res.status(404).json({
        success: false,
        error: {
          code: 'REPORT_NOT_FOUND',
          message: 'Report not found'
        }
      });
    }

    // 鍙湁绠＄悊鍛樻垨鎶ヨ〃鍒涘缓鑰呭彲浠ュ垹闄?
    if (req.user.role !== 'admin' && report.createdBy !== req.user.user_id) {
      return res.status(403).json({
        success: false,
        error: {
          code: 'FORBIDDEN',
          message: 'You can only delete your own reports'
        }
      });
    }

    await reportService.deleteReport(reportId);

    logger.info(`Report deleted by user ${req.user.username}: ${reportId}`);

    res.json({
      success: true,
      message: 'Report deleted successfully'
    });
  } catch (error) {
    next(error);
  }
});

// 鑾峰彇鎶ヨ〃鎽樿
router.get('/:reportId/summary', authenticateToken, async (req, res, next) => {
  try {
    const { reportId } = req.params;
    const report = await reportService.getReport(reportId);
    
    if (!report) {
      return res.status(404).json({
        success: false,
        error: {
          code: 'REPORT_NOT_FOUND',
          message: 'Report not found'
        }
      });
    }

    const summary = reportService.generateReportSummary(report);

    res.json({
      success: true,
      data: summary
    });
  } catch (error) {
    next(error);
  }
});

// 鑾峰彇鎶ヨ〃绫诲瀷鍒楄〃
module.exports = router;

